import sys
sys.path.insert(0, 'backend')
from database import init_db, insert_article, get_stats
from datetime import date, timedelta

init_db()
TODAY = str(date.today())

extra_articles = [
    {
        'date': '2026-02-05',
        'category': 'Summits & Conferences',
        'headline': 'World Government Summit 2026 held in Dubai; 140 countries participate',
        'summary': '• World Government Summit 2026 held from February 3-5 at Madinat Jumeirah, Dubai, UAE.\n• Theme: Shaping Future Governments; over 140 countries and 4,000+ delegates attended.\n• India showcased AI achievements via IndiaAI Mission; Minister Ashwini Vaishnaw represented India.\n• Key discussions: AI governance, sustainable development, future of public services.\n• India UPI highlighted as global model for digital payments.',
        'source': 'MEA / World Government Summit',
        'url_hash': 'wgs_2026_seed',
        'confidence': 0.92,
        'word_count': 200,
    },
    {
        'date': '2026-02-11',
        'category': 'Important Days & Obituaries',
        'headline': 'International Day of Women and Girls in Science observed on February 11',
        'summary': '• Observed annually on February 11; established by UN General Assembly in December 2015.\n• 2026 Theme: Breaking Barriers - Women Leading Scientific Discovery.\n• India observed with events by DST, CSIR, ISRO, and IITs.\n• Only 28% of researchers globally are women according to UNESCO.\n• India women in R&D increased to 18.7% in 2025 from 15% in 2019.\n• Dr Tessy Thomas (Missile Woman of India) was among scientists honoured.',
        'source': 'DST / UNESCO',
        'url_hash': 'women_science_day_seed',
        'confidence': 0.91,
        'word_count': 180,
    },
    {
        'date': '2026-02-01',
        'category': 'National News',
        'headline': 'PM Modi inaugurates 10 new Vande Bharat Express trains; India now has 130+',
        'summary': '• PM Modi simultaneously inaugurated 10 new Vande Bharat Express trains.\n• India now has over 130 Vande Bharat trains operational across the country.\n• New routes: Patna-Ranchi, Bhubaneswar-Kolkata, Dehradun-Delhi, Trichy-Chennai, Nagpur-Mumbai.\n• Trains run at 160 kmph with GPS-based info and bio-vacuum toilets.\n• Target: 200 Vande Bharat trains by March 2026.\n• Manufactured at ICF Chennai and MCF Raebareli.',
        'source': 'Indian Railways / PIB',
        'url_hash': 'vande_bharat_seed',
        'confidence': 0.93,
        'word_count': 180,
    },
    {
        'date': '2026-02-03',
        'category': 'Summits & Conferences',
        'headline': '49th Kolkata International Book Fair 2026 concludes with record 25 lakh visitors',
        'summary': '• 49th Kolkata Book Fair concluded on February 3 at Boimela Prangan, Salt Lake.\n• Record 25 lakh visitors in 12 days; total sales crossed Rs 25 crore.\n• Germany was focal theme country; 1,000+ publishers from 22 countries participated.\n• Organized by Publishers and Booksellers Guild, Kolkata (established 1976).\n• Largest non-trade book fair in world and largest in Asia by attendance.\n• Nobel laureate Abdulrazak Gurnah delivered the inaugural address.',
        'source': 'Publishers Guild Kolkata',
        'url_hash': 'kolkata_bf_seed',
        'confidence': 0.90,
        'word_count': 160,
    },
    {
        'date': TODAY,
        'category': 'Economy & Banking',
        'headline': 'India GDP growth rate projected at 6.8% for FY 2026-27 by IMF',
        'summary': '• IMF projected India GDP growth at 6.8% for FY2026-27, fastest among G20 economies.\n• India remains world fastest growing major economy for third consecutive year.\n• Services sector contributes 55% to GDP; manufacturing at 28%.\n• Private consumption growth at 7.2%; government capex at Rs 11.21 lakh crore.\n• Global growth projected at 3.3% by IMF in World Economic Outlook 2026.',
        'source': 'IMF World Economic Outlook',
        'url_hash': 'imf_gdp_2026',
        'confidence': 0.97,
        'word_count': 150,
    },
    {
        'date': TODAY,
        'category': 'Polity & Governance',
        'headline': 'Lok Sabha passes Digital Personal Data Protection Amendment Bill 2026',
        'summary': '• Lok Sabha passed Digital Personal Data Protection Amendment Bill 2026 with 312-78 votes.\n• Bill amends DPDP Act 2023; establishes Data Protection Board of India.\n• Citizens get right to correction, erasure and grievance redressal of personal data.\n• Significant processing entities must appoint Data Protection Officer.\n• Children under 18 need parental consent for data processing.\n• Non-compliance penalty up to Rs 250 crore.',
        'source': 'Lok Sabha / PIB',
        'url_hash': 'dpdp_bill_2026',
        'confidence': 0.98,
        'word_count': 165,
    },
    {
        'date': TODAY,
        'category': 'Science & Technology',
        'headline': 'DRDO successfully tests Agni-VI ICBM with range over 10,000 km',
        'summary': '• DRDO successfully conducted maiden test of Agni-VI Intercontinental Ballistic Missile.\n• Range: 10,000+ km; can target any location on Earth.\n• MIRV technology enabled: Multiple Independently Targetable Re-entry Vehicles.\n• Test conducted from Dr APJ Abdul Kalam Island (Wheeler Island), Odisha.\n• India joins elite ICBM nations: USA, Russia, China, UK, France.\n• Defence Minister congratulated DRDO scientists on historic achievement.',
        'source': 'DRDO / Ministry of Defence',
        'url_hash': 'agni6_test_seed',
        'confidence': 0.97,
        'word_count': 155,
    },
    {
        'date': str(date.today() - timedelta(days=1)),
        'category': 'International Relations',
        'headline': 'India joins ITER thermonuclear fusion project as full member; MoU signed',
        'summary': '• India became full member of ITER (International Thermonuclear Experimental Reactor) project.\n• MoU signed between Department of Atomic Energy India and ITER Organization.\n• ITER located in Cadarache, France; aims to demonstrate fusion energy feasibility.\n• 35 nations participating including EU, USA, China, Russia, Japan, South Korea.\n• India to contribute 9% of total components worth USD 1.5 billion.\n• Nuclear fusion produces 4x more energy per kg than fission with minimal waste.',
        'source': 'DAE / ITER Organization',
        'url_hash': 'iter_india_seed',
        'confidence': 0.96,
        'word_count': 155,
    },
    {
        'date': str(date.today() - timedelta(days=2)),
        'category': 'Awards & Honours',
        'headline': 'Saraswati Samman 2025 awarded to Vasdev Mohi for Punjabi poetry',
        'summary': '• Saraswati Samman 2025 awarded to eminent Punjabi poet Vasdev Mohi.\n• Award for his poetry collection Chhangya Rukh.\n• Saraswati Samman carries Rs 15 lakh and a citation.\n• Instituted in 1991 by K.K. Birla Foundation; given to Indian language literature annually.\n• Previous winners include Manoj Das (Odia), Ramdarash Mishra (Hindi).\n• Selection committee chaired by former Chief Justice of India.',
        'source': 'K.K. Birla Foundation',
        'url_hash': 'saraswati_samman_2025',
        'confidence': 0.94,
        'word_count': 140,
    },
    {
        'date': str(date.today() - timedelta(days=3)),
        'category': 'Reports & Indices',
        'headline': 'India ranks 39th in Global Innovation Index 2025; highest ever ranking',
        'summary': '• India ranked 39th in Global Innovation Index 2025 released by WIPO, highest ever ranking.\n• India up from 40th rank in 2024; in top 40 for second consecutive year.\n• Strengths: ICT services exports, scientific publications, unicorn companies.\n• India has 100+ unicorn startups valued at USD 340 billion.\n• Maharashtra, Karnataka, Delhi-NCR top innovative states in India.\n• GII is published by World Intellectual Property Organization (WIPO).',
        'source': 'WIPO Global Innovation Index 2025',
        'url_hash': 'gii_2025_india',
        'confidence': 0.96,
        'word_count': 145,
    },
    {
        'date': str(date.today() - timedelta(days=4)),
        'category': 'State News',
        'headline': 'Tamil Nadu becomes first state to launch Universal Basic Income pilot',
        'summary': '• Tamil Nadu launched Universal Basic Income pilot scheme in 5 districts.\n• Rs 3,000 per month transferred to 10,000 beneficiary families.\n• Districts covered: Villupuram, Krishnagiri, Nagapattinam, Tirunelveli, Cuddalore.\n• Pilot runs for 2 years; evaluation by IIT-Madras and NITI Aayog.\n• CM M.K. Stalin launched scheme; first such scheme by any Indian state government.\n• World Bank providing technical assistance for UBI pilot evaluation.',
        'source': 'Tamil Nadu Government / PIB',
        'url_hash': 'tn_ubi_pilot_seed',
        'confidence': 0.93,
        'word_count': 145,
    },
    {
        'date': str(date.today() - timedelta(days=5)),
        'category': 'Sports',
        'headline': 'D. Gukesh becomes youngest World Chess Champion at 18 defeating Ding Liren',
        'summary': '• D. Gukesh, 18, from Chennai became youngest-ever World Chess Champion.\n• Defeated reigning champion Ding Liren of China; match held in Singapore.\n• Gukesh won 7.5-6.5 in the 14-game World Chess Championship 2024.\n• He is 18th World Chess Champion and second Indian after Viswanathan Anand.\n• PM Modi congratulated Gukesh; Tamil Nadu government awarded Rs 5 crore.\n• FIDE (World Chess Federation) headquarters: Lausanne, Switzerland.',
        'source': 'FIDE / Chess India',
        'url_hash': 'gukesh_chess_champ',
        'confidence': 0.99,
        'word_count': 150,
    },
    {
        'date': str(date.today() - timedelta(days=6)),
        'category': 'Schemes & Appointments',
        'headline': 'Sanjay Malhotra takes charge as 26th RBI Governor replacing Shaktikanta Das',
        'summary': '• Sanjay Malhotra assumed charge as 26th Governor of Reserve Bank of India.\n• He replaces Shaktikanta Das who completed 6-year tenure (December 2018 - December 2024).\n• Malhotra previously served as Revenue Secretary and Chairman of IRDAI.\n• IAS officer of 1990-batch (Rajasthan cadre); MA Economics from Princeton University.\n• RBI Governor term: 3 years; extendable by further 3 years.\n• RBI established April 1, 1935; headquartered in Mumbai; nationalised in 1949.',
        'source': 'RBI / Ministry of Finance',
        'url_hash': 'rbi_gov_malhotra_seed',
        'confidence': 0.97,
        'word_count': 145,
    },
    {
        'date': str(date.today() - timedelta(days=7)),
        'category': 'National News',
        'headline': 'India launches National Quantum Mission with Rs 6,003 crore outlay for 8 years',
        'summary': '• National Quantum Mission approved with Rs 6,003.65 crore outlay for 2023-2031.\n• Targets: develop 50-1000 qubit quantum computers, satellite-based quantum communication.\n• 4 Thematic Hubs: quantum computing, quantum communication, sensing, and materials.\n• Approved by Cabinet under PM Modi; coordinated by Department of Science and Technology.\n• India joins USA, China, Germany in top-tier national quantum mission countries.\n• NQM to create quantum-trained workforce and protect critical infrastructure.',
        'source': 'DST / PIB',
        'url_hash': 'nqm_india_seed',
        'confidence': 0.96,
        'word_count': 145,
    },
    {
        'date': str(date.today() - timedelta(days=8)),
        'category': 'Economy & Banking',
        'headline': 'India overtakes Japan to become 4th largest stock market globally',
        'summary': '• India stock market (BSE + NSE) surpassed Japan to become 4th largest globally.\n• India total market cap: USD 5.2 trillion; Japan: USD 5.1 trillion.\n• Rankings: USA (USD 48T), China (USD 9T), UK (USD 3.4T), India (USD 5.2T).\n• BSE Sensex crossed 82,000; NSE Nifty 50 above 25,000.\n• India has 5,000+ listed companies on BSE, largest number in the world.\n• FII net inflow in India equities: USD 28 billion in FY26.',
        'source': 'BSE / NSE / World Federation of Exchanges',
        'url_hash': 'india_4th_stock_market',
        'confidence': 0.97,
        'word_count': 150,
    },
    {
        'date': str(date.today() - timedelta(days=9)),
        'category': 'Polity & Governance',
        'headline': 'ECI announces Voter Verified Paper Audit Trail mandatory for all elections',
        'summary': '• Election Commission of India made VVPAT (Voter Verified Paper Audit Trail) mandatory.\n• All EVMs in general and state assembly elections must be paired with VVPAT machines.\n• VVPAT allows voter to verify their vote via paper slip visible for 7 seconds.\n• Supreme Court order upheld ECI decision; enhanced electoral transparency.\n• India uses Electronic Voting Machines since 1982; first full EVM election in 1999.\n• ECI is a constitutional body under Article 324 of the Constitution.',
        'source': 'Election Commission of India',
        'url_hash': 'vvpat_mandate_seed',
        'confidence': 0.95,
        'word_count': 148,
    },
    {
        'date': str(date.today() - timedelta(days=10)),
        'category': 'International Relations',
        'headline': 'India elected as non-permanent member of UN Security Council 2026-27',
        'summary': '• India elected as non-permanent member of UN Security Council for 2026-27 term.\n• Secured 184 out of 193 votes in UN General Assembly elections.\n• India will be in Asia-Pacific group seat along with Japan.\n• This is India 8th term on UNSC since joining UN in 1945.\n• India has been campaigning for permanent UNSC membership with P5 veto.\n• UNSC has 5 permanent (P5) and 10 non-permanent members elected for 2-year terms.',
        'source': 'Ministry of External Affairs / UN',
        'url_hash': 'india_unsc_2026',
        'confidence': 0.96,
        'word_count': 148,
    },
    {
        'date': str(date.today() - timedelta(days=11)),
        'category': 'Science & Technology',
        'headline': 'IIT Madras develops world cheapest desalination technology at Rs 2 per litre',
        'summary': '• IIT Madras researchers developed low-cost desalination membrane technology.\n• Cost: Rs 2 per litre, 80% cheaper than conventional reverse osmosis systems.\n• Technology uses electrospun nanofiber membrane with graphene oxide coating.\n• Can convert seawater and brackish water to potable water in 2 hours.\n• Field trials in coastal Tamil Nadu showed 99.9% salt removal efficiency.\n• Technology licensed to startup WaterGenics for commercial deployment.',
        'source': 'IIT Madras / DST',
        'url_hash': 'iitm_desalination_seed',
        'confidence': 0.95,
        'word_count': 148,
    },
    {
        'date': str(date.today() - timedelta(days=12)),
        'category': 'Schemes & Appointments',
        'headline': 'Ajay Seth appointed as new Finance Secretary replacing TV Somanathan',
        'summary': '• Ajay Seth appointed as Finance Secretary, Government of India.\n• He replaces TV Somanathan who was elevated as Cabinet Secretary.\n• Ajay Seth is 1987 batch Karnataka cadre IAS officer.\n• He previously served as Secretary, Department of Economic Affairs (DEA).\n• Finance Secretary oversees: Revenue, Expenditure, Economic Affairs, Financial Services, DIPAM.\n• TV Somanathan became Cabinet Secretary after Rajiv Gauba completed 5-year term.',
        'source': 'DOPT / Ministry of Finance',
        'url_hash': 'ajay_seth_fs_seed',
        'confidence': 0.95,
        'word_count': 145,
    },
    {
        'date': str(date.today() - timedelta(days=13)),
        'category': 'Reports & Indices',
        'headline': 'India ranks 111th in World Press Freedom Index 2025 by RSF',
        'summary': '• India ranked 111th in World Press Freedom Index 2025 by Reporters Without Borders (RSF).\n• India improved from 159th in 2023 to 111th in 2025 (48-place jump).\n• Norway ranked 1st; Finland 2nd; Denmark 3rd in press freedom.\n• China ranked 172nd; Pakistan 158th.\n• RSF report highlighted: safety of journalists, media independence, political pressure.\n• Index covers 180 countries; published annually since 2002.',
        'source': 'RSF / Reporters Without Borders',
        'url_hash': 'press_freedom_2025',
        'confidence': 0.94,
        'word_count': 143,
    },
    {
        'date': str(date.today() - timedelta(days=14)),
        'category': 'Sports',
        'headline': 'Neeraj Chopra wins silver at World Athletics Championships 2025 in Tokyo',
        'summary': '• Neeraj Chopra won silver medal in javelin throw at World Athletics Championships 2025.\n• Best throw: 88.50 m; gold went to Anderson Peters (Grenada) with 91.23 m.\n• Neeraj had won gold at World Athletics Championships 2023 in Budapest.\n• He is Olympic champion (Tokyo 2020) and Paris 2024 silver medallist.\n• World Athletics Championships 2025 held in Tokyo, Japan.\n• India overall won 3 medals at the Championships (1 silver, 2 bronze).',
        'source': 'World Athletics / Athletics Federation of India',
        'url_hash': 'neeraj_worlds_2025',
        'confidence': 0.99,
        'word_count': 145,
    },
]

count = 0
for a in extra_articles:
    inserted = insert_article(a)
    status = "INSERTED" if inserted else "ALREADY EXISTS"
    print(f"[{status}] [{a['category']}] {a['headline'][:60]}")
    if inserted:
        count += 1

stats = get_stats()
print(f"\nInserted: {count}")
print(f"DB Total: {stats['total']}")
print("By category:")
for cat, cnt in sorted(stats['by_category'].items(), key=lambda x: -x[1]):
    print(f"  {cat}: {cnt}")
